options(jupyter.rich_display = F)
library(data.table)
orders <- fread("/anvil/projects/tdm/data/restaurant/orders.csv")
dim(orders)
head(orders)
table(substr(orders$created_at, 1, 7))
table(paste(year(orders$created_at), month(orders$created_at), sep = "-"))
table(format(orders$created_at, "%Y-%m"))
head(sort(table(orders$customer_id), decreasing = TRUE),1)
customer <- subset(orders, customer_id == "XW90EAP")
sort(table(format(customer$created_at, "%Y-%m")), decreasing = TRUE)
table(orders$payment_mode)
sort(table(customer$payment_mode), decreasing = TRUE)
ordersJan2020 <- subset(orders,format(created_at, "%Y-%m") == "2020-01")
table(wday(ordersJan2020$grand_total))
barplot(tapply(ordersJan2020$grand_total,factor(wday(ordersJan2020$created_at)) , sum))
